'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import styles from './apn-monitor.module.css';

type Resource = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;projectId:string;status:string;stage:string;sourceUrl:string;fields:Record<string,unknown>;observedAt:string };
type Rule = { id:string;label:string;resourceType:string;field:string;enabled:boolean };
type Template = { id:string;label:string;resourceTypes:string[];businessType?:string };
type History = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;changes:Array<{field:string;before:unknown;after:unknown}>;observedAt:string };
type Payload = { accounts:Array<{accountId:string;name:string;lastRunAt:string;status:string;resourceCount:number}>;resources:Resource[];history:History[];rules:Rule[];templates:Template[];watchlist:string[] };
const EMPTY:Payload={accounts:[],resources:[],history:[],rules:[],templates:[],watchlist:[]};
const AUTO_REFRESH_MS=60*60*1000;

function date(value:string){if(!value)return '尚未扫描';return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
function countdown(target:number,now:number){if(!target)return '等待首次同步';const seconds=Math.max(0,Math.ceil((target-now)/1000));const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);const rest=seconds%60;return [hours,minutes,rest].map(value=>String(value).padStart(2,'0')).join(':');}
function valueText(value:unknown){if(Array.isArray(value))return value.join('、')||'-';if(value&&typeof value==='object')return JSON.stringify(value);return String(value||'-');}
function typeLabel(type:string){return ({opportunity:'商机',benefit_application:'券申请',benefit_allocation:'资金分配',purchase_order:'PO'} as Record<string,string>)[type]||type;}
const STATUS_NAMES:Record<string,string>={Launched:'已上线',Approved:'已通过',Active:'进行中',Pending:'待处理',Submitted:'已提交','In Progress':'审核中',ActionRequired:'需要补充资料',Rejected:'未通过',Cancelled:'已取消',Closed:'已结束',Qualified:'已确认','Closed Lost':'已关闭','AWS Closed Lost':'AWS 已关闭',LAUNCHED:'已上线',APPROVED:'已通过',ACTIVE:'进行中',PENDING:'待处理',SUBMITTED:'已提交',IN_REVIEW:'审核中',ACTION_REQUIRED:'需要补充资料',REJECTED:'未通过',CANCELLED:'已取消',CLOSED:'已结束',QUALIFIED:'已确认',CLOSED_LOST:'已关闭',BUSINESS_APPROVAL:'业务审批',FINANCE_APPROVAL:'财务审批',VALIDATION:'资料校验',DRAFT:'草稿',COMPLETED:'已完成',FULFILLED:'已发放'};
const FIELD_NAMES:Record<string,string>={awsStage:'AWS 阶段',stage:'审批进度',status:'审批结果'};
function friendly(value:unknown){const text=valueText(value);return STATUS_NAMES[text]||STATUS_NAMES[text.toUpperCase()]||text;}
function tone(value:string){if(/launched|approved|active|fulfilled|完成|通过/i.test(value))return styles.positive;if(/action|required|rejected|inactive|失败|拒绝/i.test(value))return styles.danger;return '';}

export function ApnMonitorDashboard({userName:_userName}:{userName:string}){
  const [data,setData]=useState<Payload>(EMPTY);const [watchInput,setWatchInput]=useState('');const [showAdd,setShowAdd]=useState(false);const [adding,setAdding]=useState(false);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [notice,setNotice]=useState('');const [now,setNow]=useState(()=>Date.now());const autoLoading=useRef(false);
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const response=await fetch('/api/apn-monitor',{cache:'no-store'});const body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||'无法读取 APN 监控数据');setData(body);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{if(!silent)setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const latestRunAt=useMemo(()=>data.accounts.map(item=>item.lastRunAt).filter(Boolean).sort().at(-1)||'',[data.accounts]);
  const nextRefreshAt=latestRunAt?Date.parse(latestRunAt)+AUTO_REFRESH_MS:0;
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{const check=async()=>{if(!latestRunAt||Date.now()<Date.parse(latestRunAt)+AUTO_REFRESH_MS||autoLoading.current)return;autoLoading.current=true;try{await load(true);}finally{autoLoading.current=false;}};void check();const timer=window.setInterval(()=>void check(),15000);return()=>window.clearInterval(timer);},[latestRunAt,load]);
  async function refresh(){setRefreshing(true);setNotice('');try{const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const body=await response.json() as {error?:string;resources?:number;changes?:number};if(!response.ok)throw new Error(body.error||'同步失败');setNotice(`同步完成：监控对象 ${body.resources||0} 项，状态变更 ${body.changes||0} 项`);await load();}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setRefreshing(false);}}
  async function saveWatchlist(watchlist:string[],refreshAfter=false){const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveWatchlist',watchlist})});const body=await response.json() as {error?:string;watchlist?:string[]};if(!response.ok)throw new Error(body.error||'监控列表保存失败');setData(current=>({...current,watchlist:body.watchlist||[]}));if(refreshAfter)await refresh();else await load();}
  async function addWatched(){const ids=(watchInput.toUpperCase().match(/O\d{1,19}/g)||[]);if(!ids.length){setNotice('请输入正确的商机 ID，例如 O1178352');return;}setAdding(true);setNotice('');try{await saveWatchlist([...data.watchlist,...ids],true);setWatchInput('');setShowAdd(false);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setAdding(false);}}
  const projects=useMemo(()=>{const grouped=new Map<string,Resource[]>();for(const item of data.resources)grouped.set(item.projectId,[...(grouped.get(item.projectId)||[]),item]);return [...grouped.entries()].map(([id,resources])=>({id,resources,title:resources.find(item=>item.resourceType==='opportunity')?.title||resources[0]?.title||id}));},[data.resources]);
  return <main className={styles.shell}>
    <header className={styles.header}><div><h1>APN 业务监控</h1></div><div className={styles.actions}><button type="button" className={styles.secondary} onClick={()=>window.location.assign('/')}>返回账号管理</button><button className={styles.secondary} onClick={()=>{setWatchInput('');setShowAdd(true);}}>添加 PO</button><button className={styles.primary} onClick={()=>void refresh()} disabled={refreshing}>{refreshing?'同步中...':'立即同步'}</button></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}
    {showAdd&&<div className={styles.modalBackdrop} onMouseDown={event=>!adding&&event.target===event.currentTarget&&setShowAdd(false)}><section className={styles.addDialog} role="dialog" aria-modal="true"><div className={styles.dialogHead}><div><span>监控管理</span><h2>添加 PO</h2></div><button disabled={adding} onClick={()=>setShowAdd(false)} aria-label="关闭">×</button></div><label><span>商机 ID</span><textarea autoFocus disabled={adding} value={watchInput} onChange={event=>setWatchInput(event.target.value)} placeholder={'每行一个，例如：\nO1178352'} /></label><p>系统监控 AWS 阶段及关联券申请审批状态。首次同步仅建立基准。</p>{data.watchlist.length>0&&<div className={styles.dialogList}><span>已监控</span><div className={styles.watchTags}>{data.watchlist.map(id=><button key={id} disabled={adding} title="移除监控" onClick={()=>void saveWatchlist(data.watchlist.filter(value=>value!==id))}>{id}<b>×</b></button>)}</div></div>}<footer><button className={styles.secondary} disabled={adding} onClick={()=>setShowAdd(false)}>取消</button><button className={styles.primary} disabled={adding} onClick={()=>void addWatched()}>{adding?<><i className={styles.spinner}/><span>正在添加</span></>:'确认添加'}</button></footer></section></div>}
    <section className={styles.content}><div className={styles.categoryBar}><button className={styles.active}>WA 审批监控 <b>{projects.length}</b></button><span>每 1 小时自动同步</span><span className={styles.countdown}>刷新倒计时 <b>{refreshing?'同步中...':countdown(nextRefreshAt,now)}</b></span><small>最后同步：{date(latestRunAt)}</small></div>
      {loading?<div className={styles.empty}><i className={styles.spinner}/><span>正在加载...</span></div>:projects.length===0?<div className={styles.empty}><strong>暂无监控 PO</strong><button className={styles.secondary} onClick={()=>setShowAdd(true)}>添加 PO</button></div>:<div className={styles.projects}>{projects.map(project=>{const opportunity=project.resources.find(item=>item.resourceType==='opportunity');const benefit=project.resources.find(item=>item.resourceType==='benefit_application');return <article className={styles.project} key={project.id}><div className={styles.projectTitle}><div><h2>{project.title}</h2><small>{opportunity?.externalId||project.id.replace(/^opportunity:/,'')}</small></div><a href={opportunity?.sourceUrl} target="_blank" rel="noreferrer">打开详情</a></div><div className={styles.poStatusGrid}><div><span>AWS 阶段</span><strong className={tone(valueText(opportunity?.fields.awsStage))}>{opportunity?.fields.awsStage?friendly(opportunity.fields.awsStage):'暂无数据'}</strong>{opportunity?.fields.awsStage==='Launched'&&<small>可提交券申请</small>}</div><div><span>券申请审批</span>{benefit?<p><b>审批进度：{benefit.stage?friendly(benefit.stage):'暂无数据'}</b><b>审批结果：{benefit.status?friendly(benefit.status):'暂无数据'}</b></p>:<strong>未关联券申请</strong>}</div></div></article>})}</div>}
    </section>
  </main>;
}
