'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import styles from './apn-monitor.module.css';

type Resource = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;projectId:string;status:string;stage:string;sourceUrl:string;fields:Record<string,unknown>;observedAt:string };
type Rule = { id:string;label:string;resourceType:string;field:string;enabled:boolean };
type Template = { id:string;label:string;resourceTypes:string[];businessType?:string };
type History = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;changes:Array<{field:string;before:unknown;after:unknown}>;observedAt:string };
type Payload = { accounts:Array<{accountId:string;name:string;lastRunAt:string;status:string;resourceCount:number}>;resources:Resource[];history:History[];rules:Rule[];templates:Template[];watchlist:string[] };
const EMPTY:Payload={accounts:[],resources:[],history:[],rules:[],templates:[],watchlist:[]};

function date(value:string){if(!value)return '尚未扫描';return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
function valueText(value:unknown){if(Array.isArray(value))return value.join('、')||'-';if(value&&typeof value==='object')return JSON.stringify(value);return String(value||'-');}
function typeLabel(type:string){return ({opportunity:'商机',benefit_application:'券申请',benefit_allocation:'资金分配',purchase_order:'PO'} as Record<string,string>)[type]||type;}
const STATUS_NAMES:Record<string,string>={Launched:'已上线',Approved:'已通过',Active:'进行中',Pending:'等待处理',Submitted:'已提交','In Progress':'处理中',ActionRequired:'需要补充资料',Rejected:'未通过',Cancelled:'已取消',Closed:'已结束',Qualified:'已确认','Closed Lost':'已关闭','AWS Closed Lost':'AWS 已关闭'};
const FIELD_NAMES:Record<string,string>={awsStage:'AWS 阶段',stage:'审批进度',status:'审批结果'};
function friendly(value:unknown){const text=valueText(value);return STATUS_NAMES[text]||text;}
function tone(value:string){if(/launched|approved|active|fulfilled|完成|通过/i.test(value))return styles.positive;if(/action|required|rejected|inactive|失败|拒绝/i.test(value))return styles.danger;return '';}

export function ApnMonitorDashboard({userName}:{userName:string}){
  const [data,setData]=useState<Payload>(EMPTY);const [tab,setTab]=useState('all');const [watchInput,setWatchInput]=useState('');const [showAdd,setShowAdd]=useState(false);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch('/api/apn-monitor',{cache:'no-store'});const body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||'无法读取 APN 监控数据');setData(body);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function refresh(){setRefreshing(true);setNotice('');try{const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const body=await response.json() as {error?:string;resources?:number;changes?:number};if(!response.ok)throw new Error(body.error||'同步失败');setNotice(`同步完成：监控对象 ${body.resources||0} 项，状态变更 ${body.changes||0} 项`);await load();}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setRefreshing(false);}}
  async function toggleRule(id:string){const rules=data.rules.map(rule=>rule.id===id?{...rule,enabled:!rule.enabled}:rule);setData(current=>({...current,rules}));const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveRules',rules})});if(!response.ok){setNotice('提醒规则保存失败');await load();}}
  async function saveWatchlist(watchlist:string[],refreshAfter=false){const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveWatchlist',watchlist})});const body=await response.json() as {error?:string;watchlist?:string[]};if(!response.ok)throw new Error(body.error||'监控列表保存失败');setData(current=>({...current,watchlist:body.watchlist||[]}));if(refreshAfter)await refresh();else await load();}
  async function addWatched(){const ids=(watchInput.toUpperCase().match(/O\d{1,19}/g)||[]);if(!ids.length){setNotice('请输入正确的商机 ID，例如 O1178352');return;}setNotice('');try{await saveWatchlist([...data.watchlist,...ids],true);setWatchInput('');setShowAdd(false);}catch(error){setNotice(error instanceof Error?error.message:String(error));}}
  const filtered=useMemo(()=>{const template=data.templates.find(item=>item.id===tab);if(!template||template.id==='all')return data.resources;return data.resources.filter(item=>(!template.businessType||item.businessType===template.businessType)&&(!template.resourceTypes.length||template.resourceTypes.includes(item.resourceType)));},[data.resources,data.templates,tab]);
  const projects=useMemo(()=>{const grouped=new Map<string,Resource[]>();for(const item of filtered)grouped.set(item.projectId,[...(grouped.get(item.projectId)||[]),item]);return [...grouped.entries()].map(([id,resources])=>({id,resources,title:resources.find(item=>item.resourceType==='opportunity')?.title||resources[0]?.title||id}));},[filtered]);
  const changesToday=data.history.filter(item=>Date.now()-new Date(item.observedAt).getTime()<86400000).length;
  return <main className={styles.shell}>
    <header className={styles.header}><div><span className={styles.eyebrow}>APN OPERATIONS</span><h1>APN 业务监控</h1><p>商机阶段与券申请审批状态监控</p></div><div className={styles.actions}><Link href="/" className={styles.secondary}>返回账号管理</Link><button className={styles.secondary} onClick={()=>setShowAdd(true)}>添加 PO</button><button className={styles.primary} onClick={()=>void refresh()} disabled={refreshing}>{refreshing?'同步中...':'立即同步'}</button></div></header>
    <section className={styles.summary}><article><span>APN 账号</span><strong>{data.accounts.length}</strong><small>{data.accounts.map(item=>item.name).join('、')||'未配置'}</small></article><article><span>监控商机</span><strong>{new Set(data.resources.filter(item=>item.resourceType==='opportunity').map(item=>item.projectId)).size}</strong><small>含关联券申请</small></article><article><span>监控对象</span><strong>{data.resources.length}</strong><small>商机及券申请</small></article><article><span>24 小时变更</span><strong>{changesToday}</strong><small>状态变更记录</small></article></section>
    {notice&&<div className={styles.notice}>{notice}</div>}
    <section className={styles.scopeBar}><div><span>监控范围</span><strong>{data.watchlist.length} 个 PO</strong></div><div className={styles.watchTags}>{data.watchlist.length===0?<span>未添加监控项</span>:data.watchlist.map(id=><button key={id} title="移除监控" onClick={()=>void saveWatchlist(data.watchlist.filter(value=>value!==id))}>{id}<b>×</b></button>)}</div></section>
    {showAdd&&<div className={styles.modalBackdrop} onMouseDown={event=>event.target===event.currentTarget&&setShowAdd(false)}><section className={styles.addDialog} role="dialog" aria-modal="true"><div className={styles.dialogHead}><div><span>新增监控项</span><h2>添加 PO</h2></div><button onClick={()=>setShowAdd(false)} aria-label="关闭">×</button></div><label><span>商机 ID</span><textarea autoFocus value={watchInput} onChange={event=>setWatchInput(event.target.value)} placeholder={'每行一个，例如：\nO1178352'} /></label><p>监控 AWS 阶段及关联券申请审批状态。首次同步仅建立基准。</p><footer><button className={styles.secondary} onClick={()=>setShowAdd(false)}>取消</button><button className={styles.primary} onClick={()=>void addWatched()}>确认添加</button></footer></section></div>}
    <section className={styles.content}><div className={styles.toolbar}><div className={styles.tabs}>{(data.templates.length?data.templates:[{id:'all',label:'全部',resourceTypes:[]}]).map(template=><button key={template.id} className={tab===template.id?styles.active:''} onClick={()=>setTab(template.id)}>{template.label}</button>)}</div><span>最后同步：{date(data.accounts.map(item=>item.lastRunAt).sort().at(-1)||'')}</span></div>
      {loading?<div className={styles.empty}>正在加载监控数据...</div>:projects.length===0?<div className={styles.empty}><strong>暂无监控数据</strong><span>添加商机 ID 后执行同步，首次同步仅建立状态基准。</span></div>:<div className={styles.projects}>{projects.map(project=><article className={styles.project} key={project.id}><div className={styles.projectTitle}><div><span>监控项目</span><h2>{project.title}</h2></div><em>{project.resources.length} 项</em></div><div className={styles.resourceList}>{project.resources.map(item=><a href={item.sourceUrl} target="_blank" rel="noreferrer" className={styles.resource} key={`${item.resourceType}-${item.externalId}`}><div className={styles.resourceMain}><span>{typeLabel(item.resourceType)}</span><strong>{item.title}</strong><small>{item.externalId}</small></div><div className={styles.statuses}>{item.fields.awsStage?<span className={`${styles.status} ${tone(valueText(item.fields.awsStage))}`}>AWS 阶段：{friendly(item.fields.awsStage)}</span>:null}{item.stage?<span className={`${styles.status} ${tone(item.stage)}`}>审批进度：{friendly(item.stage)}</span>:null}{item.status?<span className={`${styles.status} ${tone(item.status)}`}>审批结果：{friendly(item.status)}</span>:null}{item.resourceType==='opportunity'&&item.fields.awsStage==='Launched'?<b>可提交券申请</b>:null}</div></a>)}</div></article>)}</div>}
    </section>
    <section className={styles.bottom}><article className={styles.panel}><div className={styles.panelTitle}><div><span>RULES</span><h2>提醒规则</h2></div><small>可独立启停</small></div><div className={styles.rules}>{data.rules.filter(rule=>['opportunity.awsStage','benefit.stage','benefit.status'].includes(rule.id)).map(rule=><label key={rule.id}><span><strong>{rule.label}</strong><small>{typeLabel(rule.resourceType)}</small></span><input type="checkbox" checked={rule.enabled} onChange={()=>void toggleRule(rule.id)}/></label>)}</div></article><article className={styles.panel}><div className={styles.panelTitle}><div><span>HISTORY</span><h2>变更记录</h2></div><small>最多显示 200 条</small></div><div className={styles.history}>{data.history.length===0?<p>暂无变更记录</p>:data.history.slice(0,20).map((item,index)=><div key={`${item.observedAt}-${item.externalId}-${index}`}><span>{date(item.observedAt)}</span><strong>{item.title}</strong><small>{item.changes.map(change=>`${FIELD_NAMES[change.field]||change.field}：${friendly(change.before)} → ${friendly(change.after)}`).join('；')}</small></div>)}</div></article></section>
  </main>;
}
