'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import styles from './apn-monitor.module.css';

type Resource = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;projectId:string;status:string;stage:string;sourceUrl:string;fields:Record<string,unknown>;observedAt:string };
type Rule = { id:string;label:string;resourceType:string;field:string;enabled:boolean };
type Template = { id:string;label:string;resourceTypes:string[];businessType?:string };
type History = { accountId:string;resourceType:string;externalId:string;title:string;businessType:string;changes:Array<{field:string;before:unknown;after:unknown}>;observedAt:string };
type Payload = { accounts:Array<{accountId:string;name:string;lastRunAt:string;status:string;resourceCount:number}>;resources:Resource[];history:History[];rules:Rule[];templates:Template[] };
const EMPTY:Payload={accounts:[],resources:[],history:[],rules:[],templates:[]};

function date(value:string){if(!value)return '尚未扫描';return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
function valueText(value:unknown){if(Array.isArray(value))return value.join('、')||'-';if(value&&typeof value==='object')return JSON.stringify(value);return String(value||'-');}
function typeLabel(type:string){return ({opportunity:'商机',benefit_application:'资金申请',benefit_allocation:'资金分配',purchase_order:'PO'} as Record<string,string>)[type]||type;}
function tone(value:string){if(/launched|approved|active|fulfilled|完成|通过/i.test(value))return styles.positive;if(/action|required|rejected|inactive|失败|拒绝/i.test(value))return styles.danger;return '';}

export function ApnMonitorDashboard({userName}:{userName:string}){
  const [data,setData]=useState<Payload>(EMPTY);const [tab,setTab]=useState('all');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch('/api/apn-monitor',{cache:'no-store'});const body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||'无法读取 APN 监控数据');setData(body);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function refresh(){setRefreshing(true);setNotice('');try{const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const body=await response.json() as {error?:string;resources?:number;changes?:number};if(!response.ok)throw new Error(body.error||'刷新失败');setNotice(`刷新完成：读取 ${body.resources||0} 项，发现 ${body.changes||0} 项变化`);await load();}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setRefreshing(false);}}
  async function toggleRule(id:string){const rules=data.rules.map(rule=>rule.id===id?{...rule,enabled:!rule.enabled}:rule);setData(current=>({...current,rules}));const response=await fetch('/api/apn-monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveRules',rules})});if(!response.ok){setNotice('提醒规则保存失败');await load();}}
  const filtered=useMemo(()=>{const template=data.templates.find(item=>item.id===tab);if(!template||template.id==='all')return data.resources;return data.resources.filter(item=>(!template.businessType||item.businessType===template.businessType)&&(!template.resourceTypes.length||template.resourceTypes.includes(item.resourceType)));},[data.resources,data.templates,tab]);
  const projects=useMemo(()=>{const grouped=new Map<string,Resource[]>();for(const item of filtered)grouped.set(item.projectId,[...(grouped.get(item.projectId)||[]),item]);return [...grouped.entries()].map(([id,resources])=>({id,resources,title:resources.find(item=>item.resourceType==='opportunity')?.title||resources[0]?.title||id}));},[filtered]);
  const changesToday=data.history.filter(item=>Date.now()-new Date(item.observedAt).getTime()<86400000).length;
  return <main className={styles.shell}>
    <header className={styles.header}><div><span className={styles.eyebrow}>PARTNER OPERATIONS</span><h1>APN 业务监控</h1><p>统一查看商机、权益申请、资金分配与 PO 的最新状态</p></div><div className={styles.actions}><span>{userName}</span><Link href="/" className={styles.secondary}>返回账号管理</Link><button className={styles.primary} onClick={()=>void refresh()} disabled={refreshing}>{refreshing?'正在同步...':'立即刷新'}</button></div></header>
    <section className={styles.summary}><article><span>监控账号</span><strong>{data.accounts.length}</strong><small>{data.accounts.map(item=>item.name).join('、')||'未配置 APN 账号'}</small></article><article><span>监控项目</span><strong>{new Set(data.resources.map(item=>item.projectId)).size}</strong><small>自动关联商机与申请</small></article><article><span>当前对象</span><strong>{data.resources.length}</strong><small>完整原始字段已留存</small></article><article><span>24 小时变化</span><strong>{changesToday}</strong><small>只有实际变化才提醒</small></article></section>
    {notice&&<div className={styles.notice}>{notice}</div>}
    <section className={styles.content}><div className={styles.toolbar}><div className={styles.tabs}>{(data.templates.length?data.templates:[{id:'all',label:'全部',resourceTypes:[]}]).map(template=><button key={template.id} className={tab===template.id?styles.active:''} onClick={()=>setTab(template.id)}>{template.label}</button>)}</div><span>最后同步：{date(data.accounts.map(item=>item.lastRunAt).sort().at(-1)||'')}</span></div>
      {loading?<div className={styles.empty}>正在读取 APN 数据...</div>:projects.length===0?<div className={styles.empty}><strong>暂无监控数据</strong><span>点击“立即刷新”建立第一份状态基准，首次扫描不会发送提醒。</span></div>:<div className={styles.projects}>{projects.map(project=><article className={styles.project} key={project.id}><div className={styles.projectTitle}><div><span>监控项目</span><h2>{project.title}</h2></div><em>{project.resources.length} 项</em></div><div className={styles.resourceList}>{project.resources.map(item=><a href={item.sourceUrl} target="_blank" rel="noreferrer" className={styles.resource} key={`${item.resourceType}-${item.externalId}`}><div className={styles.resourceMain}><span>{typeLabel(item.resourceType)}</span><strong>{item.title}</strong><small>{item.externalId}</small></div><div className={styles.statuses}>{item.fields.awsStage?<span className={`${styles.status} ${tone(valueText(item.fields.awsStage))}`}>AWS {valueText(item.fields.awsStage)}</span>:null}{item.stage?<span className={`${styles.status} ${tone(item.stage)}`}>{item.stage}</span>:null}{item.status?<span className={`${styles.status} ${tone(item.status)}`}>{item.status}</span>:null}{item.businessType==='wa'&&item.fields.awsStage==='Launched'?<b>可以提交券申请</b>:null}</div></a>)}</div></article>)}</div>}
    </section>
    <section className={styles.bottom}><article className={styles.panel}><div className={styles.panelTitle}><div><span>AUTOMATION</span><h2>提醒规则</h2></div><small>可随时开关</small></div><div className={styles.rules}>{data.rules.map(rule=><label key={rule.id}><span><strong>{rule.label}</strong><small>{typeLabel(rule.resourceType)} · {rule.field}</small></span><input type="checkbox" checked={rule.enabled} onChange={()=>void toggleRule(rule.id)}/></label>)}</div></article><article className={styles.panel}><div className={styles.panelTitle}><div><span>CHANGE LOG</span><h2>最近变化</h2></div><small>最多显示 200 条</small></div><div className={styles.history}>{data.history.length===0?<p>尚无状态变化记录</p>:data.history.slice(0,20).map((item,index)=><div key={`${item.observedAt}-${item.externalId}-${index}`}><span>{date(item.observedAt)}</span><strong>{item.title}</strong><small>{item.changes.map(change=>`${change.field}: ${valueText(change.before)} → ${valueText(change.after)}`).join('；')}</small></div>)}</div></article></section>
  </main>;
}
